### ISSUE TITLE
Applying multiple filters

### ISSUE THREAD

**Issue by terryupton** [benface/tailwindcss-filters#1]
Nice plugin @benface - quick question. if you wanted to apply multiple filters, it doesn't seem possible to do this using multiple classes (i.e fliter-greyscale filter-contrast). 
Instead would the recommended way be something like this?
`
greyscale-contrast': 'grayscale(100%) contrast(3)',
`

**Comment by benface** [comment]
Yep. To be honest this plugin is pretty "dumb", it's a simple 1:1 mapping between the config and the generated classes. All CSS properties that accept multiple values (`filter`, `transform`, `transition`, etc.) suffer from the same problem when it comes to utility classes, which is that every declaration of such a property completely overrides its value. There is no way in CSS to append or prepend values instead. Perhaps this plugin (as well as the [transforms](https://github.com/benface/tailwindcss-transforms) and [transitions](https://github.com/benface/tailwindcss-transitions) plugins) should be smart and create compound selectors automatically, such as:

```
.filter-grayscale.filter-contrast {
    filter: grayscale(100%) contrast(3);
}
```

However, responsive variants are problematic. What if you have the classes `filter-grayscale filter-contrast sm:filter-blur md:filter-sepia` on an element? You would need a ridiculous amount of selectors to cover all possibilities, such as:

```
@screen (min-width: 600px) {
    .filter-grayscale.filter-contrast.sm:filter-blur {
        filter: grayscale(100%) contrast(3) blur(5px);
    }
}
@screen (min-width: 800px) {
    .filter-grayscale.filter-contrast.sm:filter-blur.md:filter-sepia {
        filter: grayscale(100%) contrast(3) blur(5px) sepia(60%);
    }
}
```

So I don't think that's a workable solution. Instead, you can do like you said (create a composite utility), or use a wrapper element where possible:

```
<div class="filter-grayscale">
    <div class="filter-contrast">
        ...
    </div>
</div>
```
