### ISSUE TITLE
Hover classes

### ISSUE THREAD

**Issue by laszlocph** [benface/tailwindcss-filters#10]
The plugin works great, thank you.

Wondering how to make it work with `hover:filter-none`. I believe it would need extra CSS classes in this plugin.

Is this possible today?

**Comment by benface** [comment]
Hey @laszlocph, to generate a `hover:filter-none` class you need a `none` filter and the `hover` variant enabled for filters:
```js
// tailwind.config.js
module.exports = {
  theme: {
    filter: {
      'none': 'none',
    },
  },
  variants: {
    filter: ['responsive', 'hover'],
  },
  plugins: [
    require('tailwindcss-filters'),
  ],
};
```

**Comment by laszlocph** [comment]
Fantastic! It works!
