### ISSUE TITLE
[question] compatible with Tailwind 2.0?

### ISSUE THREAD

**Issue by tconroy** [benface/tailwindcss-filters#14]
Hello!

I wanted to ask if tailwindcss-filters is compatible with the latest version of tailwind (2.0)? I don't see any version above 1.2 referenced in the documentation.

Thank you!

**Comment by S1SYPHOS** [comment]
@tconroy Testing on v2 was a smooth experience so far.

**Comment by tconroy** [comment]
Thanks @S1SYPHOS! I hadn't gotten a chance to check yet, appreciate you letting me know.

**Comment by S1SYPHOS** [comment]
@tconroy You're welcome!
