### ISSUE TITLE
Add possibility to provide a function config (to receive the 'theme' helper)

### ISSUE THREAD

**Issue by MichaelDeBoey** [benface/tailwindcss-filters#2]
Hi @benface!

Thanks for providing us with this `tailwindcss` plugin!

I was wondering if you would be interested to implement the possibility to provide the plugin config as a function so it can depend on other parts of the `theme` (just like we do [by default](https://github.com/tailwindcss/tailwindcss/releases#update-your-config-file) with `backgroundColor`, `textColor` & `borderColor`).

My use-case would be to use the colors from my theme so I can create a filter that would be an overlay of a certain color with the help of the [`hex-to-css-filter`](http://npm.im/hex-to-css-filter) package and add it as following in the `plugin` section of my config file:
```js
// tailwind.config.js

const hexToCSSFilter = require('hex-to-css-filter');

module.exports = {
  theme: {
    colors: {
      facebook: '#3B5998',
    },
  },
  plugins: [
    require('tailwindcss-filters')(theme => ({
      filters: {
        none: 'none',
        facebook: hexToCSSFilter(theme('colors.facebook')),
      },
    })),
  ],
};
```

**Comment by benface** [comment]
Hey @MichaelDeBoey, yeah definitely. I'd look at a PR if you need this soon, or I can do it sometime in the next few weeks. I'm curious, what does `hexToCSSFilter()` output exactly? I looked at the documentation and it wasn't clear to me...

**Comment by MichaelDeBoey** [comment]
@benface `hexToCSSFilter` will output the exact filter you need to apply to get to the specified color, starting from totally black.  
So it would be better do `brightness(0) saturate(100%) ${hexToCSSFilter(theme('colors.facebook'))}`, so even if you start from a red image/icon, you'll get the correct color.

I'm happy to provide a PR if I find some time the coming days, but I'm not certain I can get to it tho 😕

**Comment by benface** [comment]
Hey @MichaelDeBoey I just released [v2.0.0-beta.1](https://github.com/benface/tailwindcss-filters/releases/tag/v2.0.0-beta.1) which makes this possible:

```
module.exports = {
  theme: {
    colors: {
      facebook: '#3B5998',
    },
    filter: theme => ({
        facebook: hexToCSSFilter(theme('colors.facebook')),
    }),
  },
  plugins: [
    require('tailwindcss-filters')(),
  ],
};
```

**Comment by MichaelDeBoey** [comment]
@benface Not sure if it's intended to have the plugin config into the theme itself...
I thought that would go in the `require` like in `v1.x`, no?

**Comment by benface** [comment]
No, that code is correct. I'm following the latest recommendations on plugin configuration, [as Adam stated here](https://github.com/tailwindcss/tailwindcss/issues/677#issuecomment-466694932):

> it's more flexible and consistent if we encourage that plugins claim a key in your theme instead of configuring them directly. Plugins could make this key customizable if needed for namespace collision reasons, but I bet in practice it would just work. I'm going to update all of the core plugins to source their configuration from the theme/variants sections themselves instead of being configured directly.

Please note that `v2.0.0-beta.1` of this plugin requires Tailwind `v1.0.0-beta.1` or later.

**Comment by MichaelDeBoey** [comment]
@benface Indeed I've seen this passing.

Would it be possible to just do `require('tailwindcss-filters')` tho, instead of triggering it?

**Comment by benface** [comment]
> Would it be possible to just do `require('tailwindcss-filters')` tho, instead of triggering it?

[Some](https://github.com/benface/tailwindcss-typography/tree/next) [of](https://github.com/benface/tailwindcss-transforms) [my](https://github.com/benface/tailwindcss-fluid-container) [plugins](https://github.com/benface/tailwindcss-triangles/tree/master) accept config options, so in order to remain consistent I made them all closures. This is also good for future-proofing: if a new feature ever requires this plugin to accept options, it wouldn't (necessarily) be a breaking change.

**Comment by MichaelDeBoey** [comment]
@benface Good point 🙂

**Comment by adamwathan** [comment]
One thing we could do is what PostCSS does, where a plugin can just be a function, or it can be created using something like:

```js
tailwindcss.plugin('filters', function (options) {
  return function ({ addUtilities }) {
    // ...
  }
})
```

This would let us type check on the return value of `plugin` and know to just invoke the underlying function if no options were passed. Wouldn't be a breaking change either way.

**Comment by benface** [comment]
Sounds like a good idea :)
