### ISSUE TITLE
Now Requires Unknown Dependency

### ISSUE THREAD

**Issue by 1sd15** [benface/tailwindcss-filters#5]
The plugin now requires an unknown plugin of `tailwindcss-plugin`.

Beta 2.0.0 Edition that doesn't feature that dependency works fine.

I couldn't find where in the ReadMe it said about the 'plugin' plugin?

**Comment by benface** [comment]
@1sd15 I'm sorry, but I have no idea what you are talking about. Can you be more specific? I cannot find any module called `tailwindcss-plugin`.

**Comment by 1sd15** [comment]
Hey there!

Sorry for my delay in response. When I try to install the new version of tailwindcss-filters and then run TailwindCSS it crashes my build! The issue comes from you using 'const plugin = require('tailwindcss/plugin');'.

That require there doesn't exist and I cannot find that dependency anywhere online.

**Comment by 1sd15** [comment]
Actually I am running an older version of TailwindCSS (Not moved to 2.0 yet as using your plugins transitions etc) so that could be the cause?

**Comment by 1sd15** [comment]
I apologise for any miscommunication you may have - I don't normally comment on repos.

**Comment by benface** [comment]
Sorry about that @1sd15, it was not documented but yes, the latest major version of `tailwindcss-filters` requires Tailwind CSS 1.2. I recommend updating to it as there are no breaking changes, but if you can't or don't want to, you can always install the latest 2.x version of the plugin (`npm install tailwindcss-filters@2.x`) which is compatible with Tailwind 1.0+. I added a note to that effect at the top of the README. Thank you!
